#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -option grp:alt_shift_toggle se,us &

bspc monitor DP-2 -d VII VIII IX X
bspc monitor DP-0 -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
